2019年第3回の前半にハッシュを持ってくる
perl-entrance-org/workshop-2019 pull request #19
Opened 2019-06-02 04:45 UTC by sironekotoro

- 例示のハッシュをLarryのものに変更
- ハッシュの部分については、in東京で指摘を受けた事項を幾分か反映
- コード内のフォントを等幅に変更

2019-06-02 08:15 UTC, xtetsuji requested changes
修正ありがとうございます。

上から変更箇所を眺めてみましたが、まとまった分量の差分変更の大半は順序入れ替えに伴うものだと考え、特に気になった部分を指摘してみました。

結論が出ないものについては、後日の変更でも良いと思います。

2019-06-02 08:15 UTC, xtetsuji commented on 3rd/slide.md
> +- ハッシュの操作（ keys, delete, exsts ）
`s/exsts/exists/` ですね。

2019-06-02 08:15 UTC, xtetsuji commented on 3rd/slide.md
> +ただし、要素は **名前（key）** と **値（value）** のペアで格納されます。
key を名前とする表現はどうかなと考えていたのですが、以前からこうでしたっけ。

キーという言葉が直感的でない場合はキー名が適切かと思ったのですが、より初学者に馴染みのない言葉になってしまうことが悩ましい。key を名前とすることで、delete の解説で「ハッシュの名前を消す」というような説明になってしまいますが、これがはたして分かりやすいか（無名ハッシュ＝ハッシュリファレンスになるの？とか）という疑問もあったりします。

私の中でのハッシュの一つのイメージはコインロッカーのようなもので、取り出すときにはキーが必要というもの。解錠はキーで行っていますが、格納されている個別のロッカーは番号で指定しています。ただ番号が適切な表現かというと、ハッシュのキーには文字列も指定可能で、それを番号と表現するのは違う。いわゆるIDなのですが、初学者にとって分かりやすい表現から離れていくジレンマを感じています。

すぐに結論が出そうにもないので、今回は配置変更に重点を置いた変更であるとして、後日の検討でも良さそうです。

2019-06-02 08:15 UTC, xtetsuji commented on 3rd/slide.md
> +このペアのことを **要素** と呼びます。
この key と value のペアを要素と呼ぶという説明って以前からこうでしたっけ？個人的には要素 (element) は値のことという印象が強かったもので。

2019-06-02 08:15 UTC, xtetsuji commented on 3rd/slide.md
> +値のみを順不同で受け取る `values` 関数もありますが、ここでは説明しません。
「説明しません」よりももう少し強い表現でもいいかもしれませんね。「Perl入学式のカリキュラムでは使いません」くらい？今回はこの表現に留めつつ、今後修正を考えてもいいかもしれません。

2019-06-02 08:15 UTC, xtetsuji commented on 3rd/slide.md
> +ハッシュはPerlのデータ構造の1つで、 **連想配列** とも呼ばれます。
なるべく解説を減らすという意味で、連想配列という言葉を出すべきかということを考えたのですが、この部分についても今後検討してもいいかも知れません。

連想配列という言葉が必要そうなのは主に

- Perl 4
- PHP

あたりかと思いますが、連想配列という言葉を解説すべきか、または別の場所で解説すべきかは悩みます。

多くの言語では辞書型といった別の表現をしていることもありますが、それも含めて解説するというのも違う気がしますし、この段階であまりPerl以外のプログラミング言語に興味関心を広げすぎても…という気も。講師メモのようなものを別に作成して、他のプログラミング言語の経験がある受講生がいたら口頭でそれについて触れるといった対応が良いのかな…。

2019-06-03 12:43 UTC, sironekotoro commented on 3rd/slide.md
> +- ハッシュの操作（ keys, delete, exsts ）
おおぅ、直します！

2019-06-03 12:46 UTC, sironekotoro commented on 3rd/slide.md
> +ただし、要素は **名前（key）** と **値（value）** のペアで格納されます。
このハッシュのkeyとvalueのところ、各ページで同じものを指しつつ、「名前」だったり「key」だったりで悩ましく、とりあえず統一表現にしたという意図です。

次回に向けて良い表現を考えます or サポーターから募集で

2019-06-03 12:48 UTC, sironekotoro commented on 3rd/slide.md
> +値のみを順不同で受け取る `values` 関数もありますが、ここでは説明しません。
ここは「Perl入学式のカリキュラムでは使いません」に直してしまいます。

2019-06-03 12:50 UTC, sironekotoro commented on 3rd/slide.md
> +ハッシュはPerlのデータ構造の1つで、 **連想配列** とも呼ばれます。
確かに確かに。連想配列っていうのはここだけで、この後は出てこない。
講師メモはともかく、スライドからは消しましょう。

2019-06-03 13:20 UTC, sironekotoro commented on 3rd/slide.md
> +このペアのことを **要素** と呼びます。
[2017年](https://github.com/perl-entrance-org/workshop-2017/blob/master/3rd/slide.md#%E3%83%8F%E3%83%83%E3%82%B7%E3%83%A5%E3%81%A8%E3%81%AF), [2018年](https://github.com/perl-entrance-org/workshop-2018/blob/master/3rd/slide.md)だとこうなっていて、この記述から逆算してペアを要素と呼ぶ、とした次第です。 
> しかし配列とは異なり、「数値」ではなく「名前」を使って、格納する「値」を指定します。
>    要素を指定するための「名前」を "key"、key によって指定された「値」を "value" と呼びます。

2019-06-03 13:23 UTC, sironekotoro commented
@xtetsuji  軽微なところを修正しました！

2019-06-04 02:08 UTC, xtetsuji approved these changes
修正ありがとうございます！いい感じになったのでマージします。

以前からこうだったけれど直したい部分については、後日の議論にしましょう。

2019-06-04 02:08 UTC, xtetsuji commented on 3rd/slide.md
> +ただし、要素は **名前（key）** と **値（value）** のペアで格納されます。
表現揺れですか。なるほど〜。

ここの部分は、次回サポーターが集まった時にでも表現方法を考えましょう。私の方でも、著名な書籍でどのような解説がされているかを確認してみます。

2019-06-04 02:08 UTC, xtetsuji commented on 3rd/slide.md
> +このペアのことを **要素** と呼びます。
こちらもサポーターが集まった時に記述を検討しましょう。

2019-06-04 02:09 UTC, merged