2019年第2回、第3回のスライド修正
perl-entrance-org/workshop-2019 pull request #20
Opened 2019-06-02 07:52 UTC by sironekotoro

- @xtetsuji  さんの気づきを反映 https://github.com/jpa-perl/Perl-Entrance-Committee/issues/268#issuecomment-491590324
- cssについては、コード表示部が等幅フォントになるように修正(macだけかも)

2019-06-04 02:54 UTC, xtetsuji requested changes
レビューをしようと思って気づいたのですが、コミットID 322e795 って先ほどマージした #19 にも入っていますね。

- https://github.com/perl-entrance-org/workshop-2019/pull/19/commits

GitHub のマージチェックではコンフリクトは起こらないと書かれているので、既に別ブランチ 2019_3rd でマージされた 322e795 の修正内容は二度適用されることはないようです。コンフリクトしたらやり直すということで、このプルリクエストの 2019_2nd ブランチもマージしようと思います。崩壊したら特定の場所のものを上書きして大胆に revert するという感じで。

状況が気になったので [fork 先での Network graph](https://github.com/sironekotoro/workshop-2019/network) を見たのですが、2019_3rd ブランチを作成して 322e795 の修正を行った後で、その 2019_3rd ブランチのその時点での HEAD である 322e795 から 2019_2nd ブランチを作成したように見えました（Network graph のツリー部分を右側が見えるようにドラッグしてみて下さい）。

今回はもう一つのコミット df5a1fe の 2nd/slide.md のみレビューしました。

Network graph を見た時にその時の master のみからトピックブランチが伸びて master ブランチへ合流するものに集約した方が GitHub Flow として後で追いかける際も圧倒的に見やすいと思うので、最新の master ブランチからのみのブランチ作成と master 最新化を意識してみて下さい。

2nd/slide.md だけでも diff が膨大で、配置変更がメインであると思って細部はあまり見ないようにしつつも、それでも気になった部分にコメントを入れました。

既に各拠点が走り出していることもあり致命的な部分以外の大幅な変更は抑えたいと思っていますが、いったんマージの方向でレビューしつつ細かい点については別ブランチで作業しましょう。

2019-06-04 02:54 UTC, xtetsuji commented on 2nd/slide.md
> +1. `undef`（まだ値を設定していないスカラー変数）Perl入学式では扱わない
空リストと undef の扱い、追記してくださってありがとうございます。いい感じです。

ただ、もう一歩踏み込んでそもそも書かない、書くとしてもお疲れさまでしたスライドの後の補足に盛り込むといった感じにして、ここでの受講生の精神的負担を積極的に減らしていく踏み込んだ対応もありかなと感じました。

いったんはこの修正にとどめて、サポーターが集まった時にでも今後の記述について相談することにしましょう。

2019-06-04 02:54 UTC, xtetsuji commented on 2nd/slide.md
> +my @lang        = qw(perl php ruby python java go);
qw ショートカット、使わない方針で一度書き換えしませんでしたっけ。まだ修正前だったかな…。

お疲れさまでしたスライドの後の落穂拾いに qw ショートカットが使われていますが、それ以前の 2nd/slide.md 内にてコメント以外での説明がなく qw ショートカットが2箇所使われているようです。

こちら確認してもらって良いでしょうか？

2019-06-04 12:06 UTC, sironekotoro commented
ありがとうございます、ネットワークグラフ、初めて見ました。
ブランチからブランチを切っている様がみてとれます。
自分ではmasterから分けていたつもりなのですが、これはわかりやすいです。
以降気を付けます。

2019-06-04 12:13 UTC, sironekotoro commented on 2nd/slide.md
> +1. `undef`（まだ値を設定していないスカラー変数）Perl入学式では扱わない
了解です。
Perlの偽値は５つあり、うちPerl入学式では３つ紹介します、ってのを上手くまとめきれませんでした。

2019-06-04 12:19 UTC, sironekotoro commented on 2nd/slide.md
> +my @lang        = qw(perl php ruby python java go);
落ち穂拾いのqwショートカット以前のものは消し忘れですので、修正しました。

2019-06-04 12:20 UTC, sironekotoro commented
一旦、2019_2ndブランチにmasterを取り込み、その上でプルリクを出してみます。

2019-06-04 12:30 UTC, sironekotoro commented
@xtetsuji ネットワークグラフ見ましたが、2019_2ndがmasterを乗っ取った形になってる・・・？
不安になってきた

2019-06-04 15:14 UTC, xtetsuji commented
私も Git についてあまり良くわかっていないのですが、調べてみました 💦 

[fork 先の Network graph](https://github.com/sironekotoro/workshop-2019/network) で master を探すと、master の先端は Network graph の最も左側、fork した直後のままになっています。master を fork 元に合わせるか否かは置いといて、この fork されたリポジトリに作られたブランチの大半はどうも master から fork したわけでは無さそうです。

本来の GitHub Flow だと master が真ん中に一本線で通って、そこから分岐したブランチが育ったらまた真ん中の master に合流という状態が複数のブランチで行われる（なので横に引いた数直線を弦にして半円の弧がいくつもできるようになる）のですが、この Network graph を見る限りでは、そうでもないようです。

プルリクエストの数の割にはブランチの数が少ないなと思って調べてみたら、 #15 と #19 で同じブランチ名だったりして、ブランチを切ったつもりで既存の物を伸ばしたのか、いまいち状況がわからなかったものもありました。私も差分のレビューのみをして、GitHub のマージチェックがコンフリクトを起こさないと書かれていたのを見て問題がないだろうと見逃していました。

CVS だと大事故レベル（逆に全く進めなくなるので状況がわかる）と思うのですが、今のところコンテンツが崩壊したということもなく、コンフリクトもしていないので、Git のマージは凄まじく賢いんだなと理解しています。workshop-2019 は1年限定なので、多少荒れてもコンテンツが無事であれば大丈夫でしょう。特定のコミットの時点を取り戻すことは `git checkout コミットID` でできますし、修正の取り戻しは面倒でも可能です。

ただ加えた変更が実は適用されていなかったり意図せず上書きされていたりということが今後起こらないとも言えない状況になってきたので、**いったんオープンされているプルリクエストは進めつつ、これをマージ・クローズしたところで sironekotoro/workshop-2019 はいったん削除して fork し直した方が良い**なと感じました。

fork し直した後の、想定されるブランチ作業についてざっと書いておきます。

# ブランチ作業

upstream については [GitHubでFork/cloneしたリポジトリを本家リポジトリに追従する - Qiita](https://qiita.com/xtetsuji/items/555a1ef19ed21ee42873) に準じた方法です。

## upstream の登録

fork 元ブランチを upstream として登録する

```
$ cd workshop-2019
$ git remote add upstream git://github.com/perl-entrance-org/workshop-2019.git
```

## 手元の master ブランチを upstream の master ブランチの内容に合わせる

```
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
```

やっていることは fetch でリモート upstream から全ブランチの情報を取得、checkout でカレントブランチを master にした上で、merge でカレントブランチ（master）に upstream/master の内容をマージするという流れです。

プルリクエストが Approve されてマージが行われるということは upstream/master にマージコミットが新たに追加されるので、マージが行われたら上記作業は行うべきでしょう。

## master ブランチからトピックブランチ（プルリクエストのためのブランチ）を作成する

上記の流れで master ブランチを upstream の master ブランチに追従した上で行います。

```
$ git checkout master
$ git branch トピックブランチ名
$ git checkout トピックブランチ名
```

`git branch` と `git checkout` の作業は `git checkout -b` でまとめることもできます。

トピックブランチで作業する場合は修正ブランチを間違え続けることはない（間違え続けたらプルリクエストの段階で気づく）のですが、master ブランチからトピックブランチを切るところは、 `git checkout master` を忘れるとハマります。**プロンプトにカレントブランチを表示する git-prompt を設定しておくとカレントブランチを意識し続けられるのでオススメ**です。

- https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh

これを適当なところに保存しておいて .bashrc で source で読み込むと `__git_ps1` といったシェル関数が使えるようになるので、これをプロンプト文字列 `PS1` のネタにするという感じです。

```sh
source ~/.bash-prompt.sh
PS1='\[\033[01;33m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " [\[\033[32m\]%s\[\033[0m\]]")\$ '
```

上記 PS1 は私の例です。 全体は [xtetsuji/dotfiles](https://github.com/xtetsuji/dotfiles/) 以下にあるので、もし必要であればそちらも参照してみて下さい。

## perl-entrance-org にブランチを push する場合

@sironekotoro さんも perl-entrance-org/workshop-2019 への書き込み権限はあるはずなので、sironekotoro/workshop-2019 として fork せず、perl-entrance-org/workshop-2019 を clone して、ここにブランチをプッシュしてプルリクエストを行う方法があります。

この場合、upstream を登録せずとも origin が perl-entrance-org の方になるので、手元の master ブランチを origin/master のものに追従する作業は、以下のよく知られたコマンドで行うことができます。

```sh
$ git checkout master
$ git fetch
$ git pull
```

fork するよりも、perl-entrance-org 内にブランチをプッシュした方が master 追従という意味では簡明かもしれませんね。

言葉で説明すると伝わりづらいのが Git なので、もし必要であればオフラインでレクチャーしますので気軽にお声掛け下さい。

2019-06-04 15:18 UTC, xtetsuji commented
sironekotoro/workshop-2019 は削除した方が…と書きましたが、perl-entrance-org/workshop-2019 を clone して、そこにブランチをプッシュする方法にシフトするのであれば、特に消さなくてもいいかなと思いました。

今まで sironekotoro/workshop-2019 で作成したブランチの枝構造は perl-entrance-org/workshop-2019 にも伝わっていると思いますが、ブランチ名までは伝わっていないので、sironekotoro/workshop-2019 の方は後々調査をするとなった場合に使えそうです。

2019-06-05 13:45 UTC, sironekotoro commented
夜間にめちゃ調べていただきありがとうございます・・・！
完璧に勘違いしていたこととしては、一度masterに取り込まれたブランチ名は再利用可能とばかり思っていました・・・今、改めて思うと、それはあかん！と思うんですが・・・まいったなぁ。

とりあえず、 @xtetsuji さんの以下の方針でいこうと思います。
調査用に証拠保全は必要と思いますので・・・
> sironekotoro/workshop-2019 は削除した方が…と書きましたが、perl-entrance-org/workshop-2019 を clone して、そこにブランチをプッシュする方法にシフトするのであれば、特に消さなくてもいいかなと思いました。

とりあえず、forkし直したあとの〜ってのは自分のローカルでやってみたいと思うんですが、これはマージ後の方が良いですかね？

2019-06-05 14:16 UTC, sironekotoro commented
とりあえず、手元にある 2019_4th, 2019_5th も作成したupstreamをmargeしました。

これは新規にmasterからブランチ切って、4th,5thのをcherry-pickして、綺麗なbranchを取り戻していこうと思います。

2019-06-05 15:24 UTC, xtetsuji approved these changes
新たに加えられたコミット 27e1b7f のおかげ（？）か、当初問題としていた #19 の 322e795 が無くなっていますね。

qw を削除していただいたコミット 7ae614a が済んだので、いったんマージしてこのプルリクエストはクローズしようと思います。

この後、perl-entrance-org/workshop-2019 の健全性を確認した後、fork せず perl-entrance-org/workshop-2019 にブランチをプッシュしてプルリクエストを作り、手元の master は origin/master（このリモート origin は github.com:perl-entrance-org の方）に合わせていくというスタイルを取りましょう。

2019-06-05 15:24 UTC, merged

2019-06-05 15:54 UTC, xtetsuji commented
> 完璧に勘違いしていたこととしては、一度masterに取り込まれたブランチ名は再利用可能とばかり思っていました・・・今、改めて思うと、それはあかん！と思うんですが・・・まいったなぁ。

厳密に言えば、マージして用が済んだブランチをローカルおよびリモートから削除した後であれば、同じ名前のブランチを新たに作成して使うことは出来ると思います。ただ、コミットメッセージには古い意味でのブランチ名が残っているので、あえて無理に再利用する意味も少ないでしょう。

おすすめの方針としては

- @sironekotoro さんも perl-entrance-org/workshop-2019 に書き込み権限があるので、fork せずそれを clone して master 追従を楽にする
- git-prompt を導入してカレントブランチを常に意識できるようにする（ `git branch` や `git checkout -b` を master 以外で打たない）
- ローカルの時点で Network graph を見る `git graph` サブコマンドを設定して、手元でもブランチの木構造を意識する（変な枝になったら、リモートにプッシュする前に対応する）
- master 最新化とも関連するが `git log` や `git graph` で master や origin/master が最上部に表示されるようにする

あたりでしょうか。

```
# .gitconfig より
        graph  = log --graph --date-order --all --pretty=format:'%h %Cred%d %Cgreen%ad %Cblue%cn %Creset%s' --date=short
```

コンフリクトが起こらないのを見て色々考えた結果、Git のマージアルゴリズムは結構賢いということを再認識しました。とはいえ無思慮に複雑にすればいずれ何らかの問題が起こるはずなので、このタイミングでブランチ運用の健全化を進めましょう。

これから元リポジトリ perl-entrance-org の今回のマージコミットの段階 perl-entrance-org/workshop-2019@8393ca4 の状態をチェックしますが、 @sironekotoro さんも第3回まで通してみて適用漏れ等が無いかチェックしていただけると幸いです。

私も Git はあまり良く理解しておらず、CVS 時代の勘で操作している部分も多かったのですが、今年度になってからPerl入学式を始めとした業務などの場面で Git と GitHub をよく使うようになり、最近になって色々と理解が深まっています。今回の件も怪我の功名と言えそうです。