2019 4th draft
perl-entrance-org/workshop-2019 pull request #24
Opened 2019-06-16 06:29 UTC by sironekotoro

- 従来のslide.mdについては、構成変更によるサブルーチンへの値渡し部を削除

- slide.mdを書き換えていたところ、変更量が多くなったので新規にdraft版としてのslide_draft.mdを追加
- 問題なければ、slide.mdを置き換える形にしたいです

2019-06-18 10:22 UTC, xtetsuji requested changes
修正ありがとうございます！

ざっと目を通してコメントをしてみました。今回も修正量が多かったので、後ほど追加で指摘を入れるかもしれません。

2019-06-18 10:22 UTC, xtetsuji commented on 4th/slide_draft.md
> +my %animal = ( dog_key => { name => 'Taro', color => 'brown' } );
ここのキー、上に合わせて dog にせずに dog_key にしている理由って何かありましたっけ？ざっと見た感じ、ここも dog でいいかなーと思いました。

dog_key という表記はこれ以降も散見されるので、通して見て何か不都合がないか検討する必要はありそうです。

2019-06-18 10:22 UTC, xtetsuji commented on 4th/slide_draft.md
> +Perlには`Data::Dumper`の他にも有用なモジュールが標準で数多く組み込まれています。
`JSON::PP` と `HTTP::Tiny` は Perl 5.14 以降ですが、受講生が対象とする Perl に Perl 5.12 以下は無いと考えていいですかね。

意外に CentOS （特に6以下）が生き残っていたりするので厄介ですが、RedHat はそもそも perl-core としてスプラッターをやってしまっているので、別項として扱った方が良さそうですね。

2019-06-18 10:22 UTC, xtetsuji commented on 4th/slide_draft.md
> +1. 作成したデータの `hokkaido` に `chitose`を追加し, `sapporo`を削除してください
`'sapporo'` の削除、どうやりますか？

```
%japan = (
    hokkaido => [
        "sapporo",
        "obihiro",
    ],
);
```

という構造の場合 `@{$japan{hokkaido}}` という配列の index 0 に `'sapporo'` が入っていることは確実だから `shift` することになるかと思いますが、一般論としてこれが3つ以上の要素の真ん中にあった場合はどうするんだ（やるとすれば `splice` か、作成し直し）という質問が来た時のことを考えておいたほうがいいかも。

```
%japan = (
    hokkaido => [
        "sapporo",
        "obihiro",
        "kushiro",
    ],
);
```

のときに `"obihiro"` を削除する方法です。

```
%japan = (
    hokkaido => [
        "sapporo",
        "obihiro",
        "kushiro",
    ],
);
splice @{$japan{hokkaido}}, 1, 1, (); # splice でやる方法
print "@{$japan{hokkaido}}\n";
```

2019-06-18 10:22 UTC, xtetsuji commented on 4th/slide_draft.md
> +    print %month_hash_ref{$name} . ' is ' . $name . "\n"
ここ

```
    print %month_hash_ref{$name} . ' is ' . $name . "\n"
```

より

```
    print $name . ' is ' . %month_hash_ref{$name} . "th month\n";
```

の方がハッシュが解決しようとしているデータの方向とも合致しているので理解しやすいかなと思ったのですが、他にも意図ありますでしょうか。

あとこうすると序数を表す `"th"` を切り替え無くてはならないという隠れた課題もありますね。

2019-06-18 10:22 UTC, xtetsuji commented on 4th/slide_draft.md
> +1. その中から`eagle`を取り出してください。
取り出すという言葉から `shift` するのかなという誤解を受けるかなとも思いました（最初そう思ってしまった）。ただ「参照して下さい」も初学者には分かりづらいので、悩ましいところ。

2019-06-20 13:33 UTC, sironekotoro commented on 4th/slide_draft.md
> +my %animal = ( dog_key => { name => 'Taro', color => 'brown' } );
ここ、書いていた時は「犬の集合を示すkey名」が必要に思えたのですが、今見ると必要ないですね・・・dogに直します

2019-06-20 13:38 UTC, sironekotoro commented on 4th/slide_draft.md
> +Perlには`Data::Dumper`の他にも有用なモジュールが標準で数多く組み込まれています。
かつての受講生さんで持ち込みPCがCentOSで、って人がいたので、一応補足で書いておきます。

2019-06-20 13:46 UTC, sironekotoro commented on 4th/slide_draft.md
> +1. 作成したデータの `hokkaido` に `chitose`を追加し, `sapporo`を削除してください
ここは`shift`しか考えてませんでした。
というか、うち自身が`splice`に慣れ親しんでいないからその質問も想定できませんでしたわ。
確かに、最初と最後の要素以外の消し方、ってのは聞かれる可能性がありますね。
練習問題の最後に、時間のある時の課題として追加しておきました。

2019-06-20 13:47 UTC, xtetsuji commented on 4th/slide_draft.md
> +my %animal = ( dog_key => { name => 'Taro', color => 'brown' } );
dog_key は和田さんが資料改訂に加わる前からあって、講義を眺めていて気にはなっていた部分でした。私も今回資料を通して読んでみて dog でいいと思いました。ついでに修正お願いできますでしょうか！

2019-06-20 14:01 UTC, sironekotoro commented on 4th/slide_draft.md
> +    print %month_hash_ref{$name} . ' is ' . $name . "\n"
確かに、データの方向もあってますし良いですね。
なにより、序数をつける問題が追加されるのは素晴らしいので、この方向に修正します。

2019-06-20 14:09 UTC, sironekotoro commented on 4th/slide_draft.md
> +1. その中から`eagle`を取り出してください。
あー、初見でそう思いますねうーん。
取り出し、割と便利に他のところでも使ってしまっていますね・・・やってることは参照して表示、なので、表示してみましょう、で言い換えてみました。

2019-06-20 14:12 UTC, sironekotoro commented
あ、またNetwork Graphが乱れた。ちょっと修正頑張ってみます

2019-06-20 15:18 UTC, xtetsuji commented on 4th/slide_draft.md
> +1. その中から`eagle`を取り出してください。
表示してみましょう、でいい感じに意図が伝わりますね。

2019-06-20 15:21 UTC, xtetsuji commented on 4th/slide_draft.md
> +1. 作成したデータの `hokkaido` に `chitose`を追加し, `sapporo`を削除してください
指摘した本人ではありますが、sapporo を抜くというというよりも、たまたま配列リファレンス （が指す配列）の冒頭（インデックス0）にあるsapporoを抜く、という解釈の方が自然ですね。

splice についてはスライドでは特に言及せず、講師やサポーターが把握していて質問に対応できるようにしておけば良さそうです。

2019-06-29 07:49 UTC, xtetsuji approved these changes
修正ありがとうございます！

良い感じなのでマージします。

2019-06-29 07:49 UTC, merged