2019年度 第5回の下書き
perl-entrance-org/workshop-2019 pull request #28
Opened 2019-07-02 06:41 UTC by sironekotoro

第5回の下書きです

- GET/POSTに関しては、落穂拾いへ移動
- POSTメソッドの投稿＆リダイレクトによる機能分離についても落穂拾いへ移動
- 行番号が変わる削除はできるだけ行わず、既存のコードに追記と変更を中心に行う形で例示
- mojoliciousのコードの比較についてはGitHubを都度参照する形
    - 行番号付きコードハイライトができなかった
- GitHubへのリンクは`target="_branck"`で別窓で開く書き方
    - revealupのmarkdownで書けなかったため、aタグ直書き

2019-07-30 12:44 UTC, xtetsuji requested changes
ざっとレビューしてみました。

POST については落穂拾いに追い出したのですね。時間が余ったらやるという位置づけでいいと思います。今回のサブルーチンと合わせても各拠点で時間が余りまくるということであれば落穂拾いの前に配置するでいいと思いますが、そもそものカリキュラムの POST の導入解説ももうちょっとブラッシュアップしたいところです。

2019-07-30 12:44 UTC, xtetsuji commented on 5th/slide_draft.md
> +say('Hello Perl');      # ─┘
ここの矢印は見やすいですね！

ただ、私の環境で Reveal のスライドで閲覧したところ乱れてしまったので、CSS の monospace あたりが効いていないのかもしれません。macOS が搭載している等幅フォントの名前を直接書くといった方法で回避できるのかな。

とはいえ、等幅フォントをどの講師閲覧環境でも強制できるのであれば良い手法だと思うので、ちょっと見てみてもらえますでしょうか！

2019-07-30 12:44 UTC, xtetsuji commented on 5th/slide_draft.md
> +<q>
内容の指摘ではないのですが、HTML で広い範囲の引用をする場合は q ではなく blockquote を使う方が良いかもしれません。

Reveal の制約でこうなっているのかもしれませんが、HTML的約束だと q （インライン要素）の中に div（ブロック要素）を入れることはご法度なので、q を blockquote にするか、フォント変更CSSを当てているだけの中の div を span にするといった対応を検討してみたいところです。

2019-07-30 12:44 UTC, xtetsuji commented on 5th/slide_draft.md
> +これから学習してく Mojolicious は**外部から追加しなくてはならないモジュール**です。
`s/学習してく/学習していく/` ですね。

2019-07-30 12:44 UTC, xtetsuji commented on 5th/slide_draft.md
> +また、「・・・有用？」というようなモジュールもあります。これらは<ruby>Acme<rt>アクメ</rt></ruby>モジュールと言われるジョークモジュール群です。
5回やってきた受講生にAcmeが刺さるかという部分が自信無いのですが、では何が刺さるかという代案も難しいですね。ちょっと私もここは宿題にします。

2019-07-30 12:44 UTC, xtetsuji commented on 5th/slide_draft.md
> +インターネット上では主に <ruby>Apache<rt>アパッチ</rt></ruby> や <ruby>nginx<rt>エンジンエックス</rt></ruby> といったWebサーバが利用されています。
フロントに立たせるWebサーバは Apache や Nginx なのですが、その裏の Mojolicious アプリケーションサーバは morbo ではないという解説も必要かなと思ったのですが、ちょっと初学者には蛇足な気もしますね。うーむ。

たぶん plack サポートを使うか hypnotoad を使うかのどちらかですが、こちらは講師のフォローで回避することにしましょうか。

2019-07-30 12:44 UTC, xtetsuji commented on 5th/slide_draft.md
> +`use Mojolicious::Lite;` と書くことは、上記のように書くのと同じです。
「上記のように書くのと同じ」は、厳密に言うと「上記も含む」なんですよね。上の4行を書いたからといって Mojolicious::Lite の関数が使えるわけではないので。「同じ」という言葉の解釈にもよりますが、互いに包含しあうという関係を「同じ」だとすると、ちょっと違う。

前からこうだった気がするので、この機会に直してしまいましょうか。

2019-07-30 12:44 UTC, xtetsuji commented on 5th/slide_draft.md
> +- `<!DOCTYPE html>` HTMLのバージョン5(HTML5)で書かれていることをブラウザに伝えるHTMLのマークアップです。
細かいシリーズですが、 文書型宣言 (DTD) `<!DOCTYPE` は、宣言ではあるけれどマークアップとは呼ばないかもしれません。「マークアップ」を「宣言」に変えておくくらいでいいかも。

2019-07-30 12:44 UTC, xtetsuji commented on 5th/slide_draft.md
> +};
この末尾セミコロンは、通常のサブルーチンのときには不要に見えたものが必要ということで注意しておいたほうがいいかもと思いつつ、蛇足のような気もするので悩ましいですね。うーむ。

2019-07-30 12:44 UTC, xtetsuji commented on 5th/slide_draft.md
> +Perlのモジュールの多くは<ruby>[meta::cpan](https://metacpan.org/)<rt>メタ シーパン</rt></ruby>で公開されています。
ロゴではなく名称表記としては MetaCPAN の方が正しいっぽいですね。

2019-07-30 12:44 UTC, xtetsuji commented on 5th/slide_draft.md
> +![MVCモデル](image/perl_entrance_2019_5th_03.png "MVCモデル")
私が sironekotoro/workshop-2019 2019_5th_draft ブランチからこの Markdown ファイルを Reveal を通して見たときに画像が表示されませんでした。image ディレクトリがどうも見当たらなかったという感じ。

2019-07-31 13:23 UTC, AnaTofuZ commented on 5th/slide_draft.md
> +また、「・・・有用？」というようなモジュールもあります。これらは<ruby>Acme<rt>アクメ</rt></ruby>モジュールと言われるジョークモジュール群です。
MojoやるんでOjo紹介してもいいかもですね
https://metacpan.org/pod/ojo

2019-08-03 02:30 UTC, sironekotoro commented on 5th/slide_draft.md
> +say('Hello Perl');      # ─┘
- macOS +  Firefox 68.0.1 では正常表示
- macOS + Chrome 76.0.3809.87 では表示乱れ
- macOS + Safari 12.1.2 では表示乱れなし
 
ってことで、こちらのブログ（http://neos21.hatenablog.com/entry/2017/10/22/080000）の内容をもとに修正して、手元のChromeでも等幅で表示できるようになりました。

他の会のスライドでも、等幅フォント積極的に活用していきたいです。

2019-08-03 02:39 UTC, sironekotoro commented on 5th/slide_draft.md
> +<q>
> q を blockquote にするか

これで対処しました。
それにしても、インライン要素とかブロック要素というのを知ってはいても、その拘束条件にまで知識が回ってませんでした。

2019-08-03 02:40 UTC, sironekotoro commented on 5th/slide_draft.md
> +これから学習してく Mojolicious は**外部から追加しなくてはならないモジュール**です。
修正しました

2019-08-03 02:46 UTC, sironekotoro commented on 5th/slide_draft.md
> +また、「・・・有用？」というようなモジュールもあります。これらは<ruby>Acme<rt>アクメ</rt></ruby>モジュールと言われるジョークモジュール群です。
思えば、Mojoliciuousの紹介から即ACMEに行くってのは、何というか、もうワンクッションあってもいいのでは感がありますね・・・追加してみます。

2019-08-03 03:26 UTC, sironekotoro commented on 5th/slide_draft.md
> +インターネット上では主に <ruby>Apache<rt>アパッチ</rt></ruby> や <ruby>nginx<rt>エンジンエックス</rt></ruby> といったWebサーバが利用されています。
この先に進んで行く際のとっかかりになるかなぁ、と思い、少し記述を増やしました。
が、自分自身でも理解が足りないかも。

講義の時はさらっと流すつもりです。

2019-08-03 03:30 UTC, sironekotoro commented on 5th/slide_draft.md
> +`use Mojolicious::Lite;` と書くことは、上記のように書くのと同じです。
直しました。

2019-08-03 03:31 UTC, sironekotoro commented on 5th/slide_draft.md
> +- `<!DOCTYPE html>` HTMLのバージョン5(HTML5)で書かれていることをブラウザに伝えるHTMLのマークアップです。
了解です、確かにマークアップとは違う気がしますので直しました。

2019-08-03 03:46 UTC, sironekotoro commented on 5th/slide_draft.md
> +};
あー、ここは確かに・・・

第5回冒頭でやったサブルーチンではブロック最後のセミコロンいらないのに、ここではなぜ？となりますよね。

書き足しておいて、講義ではさらっと流すようにしたいと思います。

2019-08-03 03:47 UTC, sironekotoro commented on 5th/slide_draft.md
> +Perlのモジュールの多くは<ruby>[meta::cpan](https://metacpan.org/)<rt>メタ シーパン</rt></ruby>で公開されています。
正確な表記でやっていきたいと思うので、直します！

2019-08-03 05:42 UTC, sironekotoro commented on 5th/slide_draft.md
> +![MVCモデル](image/perl_entrance_2019_5th_03.png "MVCモデル")
imageディレクトリと画像を追加しました。

2019-08-03 06:39 UTC, sironekotoro commented
- GitHubに掲載しているリンクには [GitHub] とプリフィックスを追加
- 句読点欠け、画面はみ出しなど、細かいところの調整

すみません、今思えば [GitHub]のプリフィックス追加は別コミットにすべきでした・・・

2019-08-03 06:42 UTC, xtetsuji commented on 5th/slide_draft.md
> +インターネット上では主に <ruby>Apache<rt>アパッチ</rt></ruby> や <ruby>nginx<rt>エンジンエックス</rt></ruby> といったWebサーバが利用されています。
講義終了スライド後の落穂拾いに詰め込むでもいいかもしれません。

2019-08-03 12:39 UTC, xtetsuji requested changes
再度の修正ありがとうございます！

等幅フォントになったことで、アスキーアートでの指示も書けるようになって良い感じになりました。

やるかどうかは要検討ですが、sironekotoro/mojo_fizzbuzz_2019 については perl-entrance-org にリポジトリを移動させてもいいかもしれませんね。

typo があったので、そこの修正だけお願いします。深く見ていくとまた色々修正点が出てくると思いますが、現状はドラフトという位置づけなので、いったんマージしたいと思います。

2019-08-03 12:39 UTC, xtetsuji commented on 5th/slide_draft.md
> +Controllrer から受け取った情報を表示します。
Controllrer typo です！

2019-08-03 12:39 UTC, xtetsuji commented on 5th/original.css
> +  font-family: "Courier New", Consolas, monospace; }
私の macOS Google Chrome 環境でも等幅フォントとしてバッチリ見えるようになりました。

今までのソースコード部分がプロポーショナルフォントで違和感があった部分も解消され、良い感じになりました。

2019-08-07 02:14 UTC, sironekotoro commented on 5th/slide_draft.md
> +Controllrer から受け取った情報を表示します。
typo、直しました！

2019-08-07 02:15 UTC, sironekotoro commented
「コントローラ」「コントローラー」と表記が揺れていたので、「コントローラー」に表記を統一しています。

2019-08-07 02:17 UTC, sironekotoro commented
> typo があったので、そこの修正だけお願いします。深く見ていくとまた色々修正点が出てくると思いますが、現状はドラフトという位置づけなので、いったんマージしたいと思います。

確認ありがとうございました。
先のtypo修正したものでリリースしたいのですが、これは既存の第五回と置き換えて今回の版でこ上書きしてしまって良いでしょうか？

2019-08-09 07:04 UTC, xtetsuji commented
慌ただしくて再レビュー漏れていました。

こちらマージしますので、その後で置き換えお願いできますでしょうか！

2019-08-09 07:05 UTC, merged

2019-08-09 08:02 UTC, xtetsuji commented
操作に焦ってレビューから Approve できていませんでしたが、差分は確認して問題なさそうだということは確認済みです :bow: