HTML入学式のスライド版を追加
perl-entrance-org/workshop-2019 pull request #32
Opened 2019-07-23 04:03 UTC by sironekotoro

第4回のおまけコンテンツとして、revealupのmarkdownに対応したものを追加

2019-09-08 09:51 UTC, xtetsuji requested changes
修正ありがとうございます！大枠は大丈夫だと思いました。

第5回も含めた修正になるので個別に指摘はしなかったのですが、POST リクエストを投げる先の URL が `/post` は、ちょっと混乱するので分かりづらいなーと改めて思いました。これは別の場所で議論しましょう。

2019-09-08 09:51 UTC, xtetsuji commented on 4th/html_entrance.md
> +- <a href="https://support.microsoft.com/ja-jp/help/17621/internet-explorer-downloads" target="_brank">Internet Explorer(Microsoft)</a>
細かいですが、Microsoft Windows の現在のデフォルトブラウザは Edge ですが、併記したほうがいいですかね。それとも「そんなものはない（中身 Chrome と一緒だし）」という態度を貫いてもいいかなとも思いました。

2019-09-08 09:51 UTC, xtetsuji commented on 4th/html_entrance.md
> +<タグ>なかみ</タグ>
もともと要素というものがあって、要素の開始と終端を明示するのが開始タグと終了タグではあるのですが、初学者にはこの定義はちょっと難しいかも。

逆の導入となりますが、開始タグと中身と終了タグをあわせた全体のことを要素と言うことは書いておいてもいいかなと思いました。要素という言葉を一度出しておけば、わかりやすさのために要素の意味でタグという言葉を使うのはアリだと思います。

HTML 的には開始タグと終了タグで囲われる「中身」の正式な用語は「内容 (content)」ですね。

2019-09-08 09:51 UTC, xtetsuji commented on 4th/html_entrance.md
> +### 1行目 DOCTYPEタグ
DOCTYPE は「タグ」ではなくて「宣言」としておいたほうがいいかも。初学者からすると「タグのようなもの」ではあるので、難しさはありますね。

ちなみに宣言に使われる `<! 〜〜〜 >` 構文の中では `--` で囲まれた内容がコメントになるので、これを応用したものが HTML コメントとなっています。なので HTML コメントもタグではないといえる…のかな？？？

`<! 〜〜〜 >` はタグのように見えてタグではない、と教えてしまう方が良いかも。

2019-09-08 09:51 UTC, xtetsuji commented on 4th/html_entrance.md
> +HTMLはそのままでは静的（ページ内容が書き変わらないもの）ですが、Perl や JavaScript の力を借りることで書き換えが可能になります。
「書き換え」というと、保存している `.html` なファイルをサーバ側でエディタで編集しているという印象を持ってしまう受講生もいそう。

「書き換え」というよりは「状況に応じた出力」ではあるのですが、私もこの辺りバシッと決まった文言が思いつかなかったので、いったんスルーでいいかもしれません。

2019-09-08 09:51 UTC, xtetsuji commented on 4th/html_entrance.md
> +CSS や Javascript にもバージョンがあり、さらにブラウザも種類やバージョンごとに HTML の解釈が異なる場合があります。
`s/Javascript/JavaScript/`

2019-09-10 09:43 UTC, sironekotoro commented on 4th/html_entrance.md
> +- <a href="https://support.microsoft.com/ja-jp/help/17621/internet-explorer-downloads" target="_brank">Internet Explorer(Microsoft)</a>
デフォルトブラウザで、ページにも余裕があるので追加しました

2019-09-10 09:53 UTC, sironekotoro commented on 4th/html_entrance.md
> +<タグ>なかみ</タグ>
「要素」の解説がないのは盲点でした・・・というか、うちの盲点が洗い出されている感。
追加しました。

2019-09-10 09:53 UTC, sironekotoro commented on 4th/html_entrance.md
> +### 1行目 DOCTYPEタグ
DOCTYPE宣言にしました

2019-09-10 09:54 UTC, sironekotoro commented on 4th/html_entrance.md
> +HTMLはそのままでは静的（ページ内容が書き変わらないもの）ですが、Perl や JavaScript の力を借りることで書き換えが可能になります。
静的な方は、「状況に応じた出力」で、JavaScriptの方はそのまま「書き換え」で残してみました。
ちょっと自信がない。

2019-09-10 09:55 UTC, sironekotoro commented on 4th/html_entrance.md
> +CSS や Javascript にもバージョンがあり、さらにブラウザも種類やバージョンごとに HTML の解釈が異なる場合があります。
修正しました

2019-09-10 09:55 UTC, sironekotoro commented
その他、現時点で気になったところを修正

2019-09-11 11:02 UTC, xtetsuji approved these changes
いい感じになりましたのでマージします！

2019-09-11 11:02 UTC, merged