Fix 2019 1st part1
perl-entrance-org/workshop-2019 pull request #42
Opened 2019-09-12 12:59 UTC by sironekotoro

- CSS修正に伴う、本文の修正
- 一部文章の修正

2019-09-14 12:36 UTC, xtetsuji commented
@sironekotoro ついでに作業のお願いなのですが、カギ括弧がいわゆる半角になっている部分がありますが、これをいわゆる全角に直してもらえますでしょうか！

以下のように直接検索対象とすることで洗い出せます。私がやったところ 1st/part1.md では2行ありました。

```
perl -MTerm::ANSIColor=colored -ne 's/｢|｣/colored($&, "white on_red")/eg and print ' 1st/part1.md
```

- いわゆる全角
    - `「` [U+300C](https://unicode-search.net/unicode-namesearch.pl?term=300C) LEFT CORNER BRACKET
    - `」` [U+300D](https://unicode-search.net/unicode-namesearch.pl?term=300D) RIGHT CORNER BRACKET
- いわゆる半角
    - `｢` [U+FF62](https://unicode-search.net/unicode-namesearch.pl?term=FF62) HALFWIDTH LEFT CORNER BRACKET
    - `｣` [U+FF63](https://unicode-search.net/unicode-namesearch.pl?term=FF63) HALFWIDTH RIGHT CORNER BRACKET

半角の上記は、もともとは Shift_JIS のいわゆる半角カナと同じグループにあり、互換性のために Unicode に取り入れられたものです。ただエディタによっては禁則処理に問題があったり、勝手に全角版に変換することによって編集時に混乱が起こったりする問題もあり、全角版と半角版が混在している状況を全角に統一したいと考えています。

置換作業自体は以下のワンライナーで行えると思います。

```
perl -p -i -e 's/｢/「/g; s/｣/」/g' 1st/part1.md
```

2019-09-15 01:13 UTC, sironekotoro commented
あー、いくつか気にはなっていましたが、そのままスルーしてました。

ありがとうございます、ワンライナーで一発置換おkでした。

2019-09-20 15:12 UTC, xtetsuji requested changes
修正ありがとうございます！レビューしてみました！

今年度傍観していた第1回第1部の反響を元に、大胆に手を入れていこうかと思っていましたが、どちらかというとオフラインサポーターミーティング等で議論したほうがいいかなと思ったので、いったん切り込んでいかないようにしました。

2019-09-20 15:12 UTC, xtetsuji commented on 1st/part1.md
>  ## msys2とは?
msys2 最初の英語の引用スライド、このスライドを読むことはないなと思いました。このスライドを削除して、次の日本語の意訳のスライドに元サイトへのリンクなどを混ぜたいです。

2019-09-20 15:12 UTC, xtetsuji commented on 1st/part1.md
>  ## msys2のインストール時の推奨環境
私の環境だけかもしれませんが、ちょうど1文字だけ2行目に追い出されるようです。

「msys2のインストール時」を「msys2インストール時」に代えてみたいかも！

2019-09-20 15:12 UTC, xtetsuji commented on 1st/part1.md
> +msys2でPerlの開発環境を構築する際、約1GBのストレージ容量を必要とします。
自然文だったので箇条書きから文に変換してくれたと思いますが、必要なものだけ抜き出して箇条書きにし直すのも良さそうだと思いました。

- ストレージ：1GB以上
    - Cドライブ容量が少ない場合、DドライブやUSBメモリなどを活用しましょう
- CPU：Windowsが快適に動かせる量、64bitを推奨
- メモリ：Windowsが快適に動かせる量
- アンチウィルスソフト：一部アンチソフトで誤検知の可能性あり
    - Windows Defender を推奨します
- 不安に思ったらサポーターに質問して下さい

…みたいな感じかなー。

次のページでCPUのビット数を確認するスライドがあったので、そのクッションとしてCPUについての項目を入れてあります。

ただ、以後も文章が続いているので、ここだけを箇条書きにしてバランスが悪くなる可能性もあり、やるのであれば別ブランチで箇条書き変換作業をまとめてした方が良いかなと思っています。

2019-09-20 15:12 UTC, xtetsuji commented on 1st/part1.md
> +1. 右上の×ボタンをおしてウィンドウを閉じます
「おして」を漢字表記「押して」にしておきましょうか。

正式な表記は何だろうと考えてみたのですが、「クリック」もタッチディスプレイ全盛の世の中で廃れてゆく単語かもしれません。「押して」「選択して」あたりなのでしょうが、閉じるボタンは選択している感があまりないので「押して」が一番しっくりくる気がしています。

2019-09-23 01:51 UTC, sironekotoro commented on 1st/part1.md
>  ## msys2とは?
たしかに、ここは都度読み上げているわけではなかったですし・・・。日本語訳の下に原文へのリンクを追加しました。

2019-09-23 01:55 UTC, sironekotoro commented on 1st/part1.md
>  ## msys2のインストール時の推奨環境
確かに1文字出っ張ってましたので、「の」を削りました。

2019-09-23 01:57 UTC, sironekotoro commented on 1st/part1.md
> +1. 右上の×ボタンをおしてウィンドウを閉じます
修正しました。

2019-09-23 01:58 UTC, sironekotoro commented on 1st/part1.md
> +msys2でPerlの開発環境を構築する際、約1GBのストレージ容量を必要とします。
たしかに、例示してもらった箇条書きに特化した書き方の方がわかりやすいです。このP/R終わったら別ブランチ立ててやります。

2019-09-24 02:36 UTC, xtetsuji approved these changes
修正ありがとうございます！マージします。

内容に切り込んだ大胆な修正は、Issue を立てたりオフラインサポーターミーティング等で議論したりしていければと考えています。

2019-09-24 02:36 UTC, merged