Fix 2019 autumn 1st part2
perl-entrance-org/workshop-2019 pull request #50
Opened 2019-12-01 02:54 UTC by sironekotoro

2019年in東京 秋開講で耳にした改善案です。主に以下2点です。
- linuxコマンドの由来を追加
- VSCodeメニューの日本語化

2019-12-03 11:19 UTC, xtetsuji requested changes
修正ありがとうございます！

ざっと目についた部分をレビューしてみました。文言系なので重箱の隅っぽくなってしまったのはご容赦下さい。

2019-12-03 11:19 UTC, xtetsuji commented on 1st/part2.md
> +`touch`にはは2つの役割があります。`touch FILENAME` とした時・・・
「は」が重複しているので削除お願いします！

2019-12-03 11:19 UTC, xtetsuji commented on 1st/part2.md
> +- FILENAME がすでに存在する場合には、ファイルの作成日時を現時刻に書き換える
これ、一般的には「作成日時」ではなく「アクセス日時と更新日時」かなと思いました。

2019-12-03 14:24 UTC, sironekotoro commented on 1st/part2.md
> +- FILENAME がすでに存在する場合には、ファイルの作成日時を現時刻に書き換える
指摘事項、修正しました！

2019-12-04 03:45 UTC, xtetsuji approved these changes
修正ありがとうございます！マージします！

2019-12-04 03:45 UTC, merged